version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - ldio-net

  ldio:
    image: ghcr.io/yalz/ldio:latest
    ports:
      - '8080:8080'
    environment:
      - REDIS_URI=redis://default:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379
    depends_on:
      - cache
    networks:
      - ldio-net

volumes:
  cache:
    driver: local

networks:
  ldio-net:
    driver: bridge
