name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  backend:
    name: Build Backend Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Generate Dockerfile
        run: ./gradlew dockerfile

      - name: Build backend
        run: ./gradlew :ldio-core:clean :ldio-core:build :ldio-core:dockerfile

      - name: Build Docker image
        run: docker build -t ghcr.io/yalz/ldio:latest -f ldio-core/build/docker/main/Dockerfile ldio-core/build/docker/main/

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Yalz --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/yalz/ldio:latest

  frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Vite frontend Docker image
        run: docker build -t ghcr.io/yalz/ldio-ui:latest -f frontend/Dockerfile frontend/

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Yalz --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/yalz/ldio-ui:latest
