name: Native Build & Docker Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1.3.5
        with:
          java-version: '24'
          distribution: 'graalvm'
          native-image: true

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Build native image
        run: ./gradlew dockerPush
